global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
    - to: assafxdori@gmail.com
      from: alertmanager@gmail.com
      headers:
        subject: 'Alertmanager Alert!'
      smarthost: smtp.gmail.com:587
      auth_username: assafxdori@gmail.com
      auth_identity: assafxdori@gmail.com
      auth_password: abc123
      send_resolved: true
