name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.1

      - name: Initialize Terraform
        run: terraform init

    #   - name: Plan Terraform deployment
    #     run: terraform plan

    #   - name: Apply Terraform changes
    #     run: terraform apply -auto-approve
