name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    #needs:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'

    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id:      ${{     secrets.AWS_ACCESS_KEY_ID      }}
          aws-secret-access-key:  ${{     secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region:             ${{         env.AWS_REGION             }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Install
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.1

      - name: Terraform Initialize
        working-directory: terraform
        run: terraform init

      - name: Terraform State List
        working-directory: terraform
        run: terraform state list

      - name: Terraform Plan deployment
        working-directory: terraform
        run: terraform plan

    #   - name: Terraform Apply changes
    #     working-directory: terraform
    #     run: terraform apply -auto-approve