name: CI Workflow

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE_NAME: asixl/cli-resume:github
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Test the Docker image
        run: docker run --rm ${{ env.DOCKER_IMAGE_NAME }} /bin/sh -c echo "Docker image test successful!"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}

    