name: CI/CD Workflow - Production

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE_NAME: asixl/cli-resume:github
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Test the Docker image
        run: docker run --rm ${{ env.DOCKER_IMAGE_NAME }} /bin/sh -c echo "Docker image test successful!"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}


  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'

    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id:      ${{     secrets.AWS_ACCESS_KEY_ID      }}
          aws-secret-access-key:  ${{     secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region:             ${{         env.AWS_REGION             }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Install
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.1

      - name: Terraform Initialize
        working-directory: terraform
        run: terraform init

      - name: Terraform State List
        working-directory: terraform
        run: terraform state list

      - name: Terraform Plan deployment
        working-directory: terraform
        run: terraform plan

    #   - name: Terraform Apply changes
    #     working-directory: terraform
    #     run: terraform apply -auto-approve

    